language: python
python:
  - "3.6"

services:
  - docker
# 나머지는 docker에서 관리하므로 등록할 필요 X

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  
